### ISSUE TITLE
permit setting velero replicas

### ISSUE THREAD

**Issue by ajchiarello** [vmware-tanzu/helm-charts#49]
I notice that the helm chart does not currently have an option to set the number of velero replicas - instead, it defaults to 1 replica. Unless there is a reason that more than one replica of the velero pod should be run, please add the option to set the replica count on install.

**Comment by jenting** [comment]
The only reason I could thought on change the #replicas is for pod HA.
@ajchiarello Could you please elaborate on the use case to change the #replicas?

**Comment by ajchiarello** [comment]
@jenting pod HA and deployment resiliency is my use case. If a particular node goes down, I still want the velero deployment to persist uninterrupted.

**Comment by jenting** [comment]
@ajchiarello could you please file a PR for this enhancement if possible? thanks.

**Comment by carlisia** [comment]
Hey @ajchiarello this is a good request. It's also the type of request that should be open on the Velero repo, since any new feature would be ported to the chart after it exists in Velero.

With all that said, we currently cannot have more than 1 replica of Velero running. 

If the node goes down, the pod should just get rescheduled onto a new node. The Velero service doesn't really need to be running continuously, a short break will be fine since it will pick up any operation added to the queue.

We do have plans to increase performance and make operations faster, please see: https://github.com/vmware-tanzu/velero/issues?q=is%3Aopen+is%3Aissue+label%3APerformance

Closing this.
