### ISSUE TITLE
uploader-type default should be kopia

### ISSUE THREAD

**Issue by andrewhibbert** [vmware-tanzu/helm-charts#549]
**What steps did you take and what happened:**

The docs say `uploader-type` will default to kopia if empty in https://velero.io/docs/main/file-system-backup/ "Path selection". The helm chart defaults to restic - [charts](https://github.com/vmware-tanzu/helm-charts/blob/main/charts/velero/templates/deployment.yaml#L89)

**Comment by qiuming-best** [comment]
@jenting OK

**Comment by pschichtel** [comment]
isn't this a breaking change for everyone that didn't explicitly set restic?

**Comment by jenting** [comment]
> isn't this a breaking change for everyone that didn't explicitly set restic?

yes, we missed to bump the minor version :(

**Comment by cwrau** [comment]
> > isn't this a breaking change for everyone that didn't explicitly set restic?
> 
> yes, we missed to bump the minor version :(

I've said this before, although I can't find it now, but people rely on versioning!

And not only did you miss to bump the version, you wanted to bump the minor version for a breaking change?!

Breaking changes are major version bumps, see https://semver.org

---

For this reason, [you are the only chart of dozens of charts that we're using that has a pinned version](https://github.com/teutonet/teutonet-helm-charts/pull/781), as we can't rely on this.

**Comment by pschichtel** [comment]
@cwrau who said they follow semver? not every project does. You shouldn't just use version ranges assuming semver. Or if you do, you do it accepting a certain risk. I noticed the change while reading changelog (as you should do for important software) and asked if I'm understanding it correctly.

**Comment by cwrau** [comment]
> @cwrau who said they follow semver? not every project does.

I guess so, but then they should state that somewhere, as semver has been the defacto standard for a couple of years now.

And if they don't follow semver, I'd kindly ask them to do it, as semver is extremely helpful in conveying information without the need to dig deep.

> You shouldn't just use version ranges assuming semver.

In light of this, yes, now we're going to look deeper at versioning of other projects.
But semver has been the defacto standard for years now, it's like assuming a car has a seatbelt.
I never saw a car without it and now velero is the first project I've come across to _not_ adhere to semver

> Or if you do, you do it accepting a certain risk.

Yeah, that's why we had to switch to a pinned version for velero 🙄

**Comment by pschichtel** [comment]
Honestly I know very few projects that stick to semver close enough for me to blindly follow it. I always decide on a project by project basis. It's always a discussion of "is this change breaking enough to warrant a major version change", many projects accept minor breakages, but the impact might still be huge for you. 

But maybe I've been burned to many times and just got overly cautious. Anyway, I guess feel free to open a request for stricter semver.
